### ISSUE TITLE
installation failed..

### ISSUE THREAD

**Issue by EMCP** [kylemcdonald/AudioNotebooks#1]
while attempting to install requirements I got tripped up looking for `samplerate`

Guessing it's an issue with me running python 3.5 , see https://github.com/cournape/samplerate/issues/8

```
~/Dev/gitroot/EMCP/kylemcdonald/AudioNotebooks (master)$ pip3 install -r requirements.txt 
Collecting jupyter (from -r requirements.txt (line 1))
  Using cached jupyter-1.0.0-py2.py3-none-any.whl
Collecting librosa (from -r requirements.txt (line 2))
  Using cached librosa-0.4.3.tar.gz
Requirement already satisfied: numpy in /usr/local/lib/python3.5/site-packages (from -r requirements.txt (line 3))
Collecting scikits.samplerate (from -r requirements.txt (line 4))
  Using cached scikits.samplerate-0.3.3.tar.gz
    Complete output from command python setup.py egg_info:
    SamplerateInfo:
      libraries samplerate not found in /usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib
      libraries samplerate not found in /usr/local/lib
      libraries samplerate not found in /usr/lib
    Traceback (most recent call last):
      File "scikits/samplerate/setup.py", line 15, in configuration
        sf_config = sf_info.get_info(2)
      File "/usr/local/lib/python3.5/site-packages/numpy/distutils/system_info.py", line 578, in get_info
        raise self.notfounderror(self.notfounderror.__doc__)
    numpy.distutils.system_info.NotFoundError: Some third-party program or library is not found.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/2c/c_kpmrvd0kd4m84wqgj28lj00000gn/T/pip-build-mx_tg_v6/scikits.samplerate/setup.py", line 74, in <module>
        classifiers = CLASSIFIERS,
      File "/usr/local/lib/python3.5/site-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "/private/var/folders/2c/c_kpmrvd0kd4m84wqgj28lj00000gn/T/pip-build-mx_tg_v6/scikits.samplerate/setup.py", line 59, in configuration
        config.add_subpackage(DISTNAME)
      File "/usr/local/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 1001, in add_subpackage
        caller_level = 2)
      File "/usr/local/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 970, in get_subpackage
        caller_level = caller_level + 1)
      File "/usr/local/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 907, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scikits/samplerate/setup.py", line 20, in configuration
        [samplerate].""")
    numpy.distutils.system_info.NotFoundError: SRC (http://www.mega-nerd.com/SRC/) library not found.  Directories to search
    for the libraries can be specified in the site.cfg file, in section
    [samplerate].
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/2c/c_kpmrvd0kd4m84wqgj28lj00000gn/T/pip-build-mx_tg_v6/scikits.samplerate/
~/Dev/gitroot/EMCP/kylemcdonald/AudioNotebooks (master)$ 
```

**Comment by kylemcdonald** [comment]
i think the latest versions of librosa replaced the requirement of samplerate with something that's easier to install. until i get a chance to update this repo (as it's almost year old now) i recommend installing the dependencies by hand and looking into the respective repos for advice.

**Comment by EMCP** [comment]
perhaps before I open a new ticket I'll post what I'm seeing while trying to follow your advice.

I went ahead and `pip3 install`'d all the packages from`requirements.txt` however when trying to run the `Collect Samples` it's complaining of a missing module

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-0a30024b4ca1> in <module>()
      1 import numpy as np
      2 from os.path import join
----> 3 from utils import *
      4 from multiprocessing import Pool

/home/emcp/Dev/gitroot/EMCP/kylemcdonald/AudioNotebooks/utils/__init__.py in <module>()
----> 1 from list_all_files import list_all_files
      2 from ffmpeg_load_audio import ffmpeg_load_audio
      3 from ffmpeg_save_audio import ffmpeg_save_audio
      4 from show_array import show_array
      5 from make_mosaic import make_mosaic

ImportError: No module named 'list_all_files'
```

**Comment by EMCP** [comment]
@kylemcdonald also noticing that `skimage` and `sklearn` no longer exists ..

perhaps it is now renamed `scikit-image` & `scikit-learn` respectively ??  Cannot be sure 

http://scikit-image.org/docs/dev/install.html

One last question, is it implied that you're using python 2.x with this notebook?  Thank you!

**Comment by kylemcdonald** [comment]
@EMCP yes python 2.x. i will update requirements.txt. thanks!
